//
//  RuntimeInspection.swift
//  RuntimeHeaders
//

import RuntimeInspectorKit

typealias InspectableMethodReturnKind = RuntimeInspectorKit.InspectableMethodReturnKind
typealias RuntimeInstanceCandidateKind = RuntimeInspectorKit.RuntimeInstanceCandidateKind
typealias RuntimeInstanceCandidate = RuntimeInspectorKit.RuntimeInstanceCandidate
typealias RuntimeInstanceResolutionOptions = RuntimeInspectorKit.RuntimeInstanceResolutionOptions


typealias InspectableProperty = RuntimeInspectorKit.InspectableProperty
typealias InspectableMethod = RuntimeInspectorKit.InspectableMethod
typealias InspectableMethodArgument = RuntimeInspectorKit.InspectableMethodArgument
typealias InspectableMethodArgumentKind = RuntimeInspectorKit.InspectableMethodArgumentKind
typealias InvocationResult = RuntimeInspectorKit.InvocationResult
typealias RuntimeInvocationArgument = RuntimeInspectorKit.RuntimeInvocationArgument


typealias RuntimeInspectionSubjectKind = RuntimeInspectorKit.RuntimeInspectionSubjectKind
typealias ResolvedRuntimeInstance = RuntimeInspectorKit.ResolvedRuntimeInstance


typealias RuntimeObjectInspectorViewModel = RuntimeInspectorKit.RuntimeObjectInspectorViewModel
